# Hyper parameter Tuning by  GridSearchCV from Sklearn

In [60]:
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()


In [61]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)

In [62]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=.3)

In [64]:
model = svm.SVC(kernel='rbf',C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9333333333333333

In [65]:
from sklearn.model_selection import cross_val_score

In [66]:
cross_val_score(svm.SVC(kernel='rbf',C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [67]:
cross_val_score(svm.SVC(kernel='rbf',C=30, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [68]:
cross_val_score(svm.SVC(kernel='linear',C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [69]:
cross_val_score(svm.SVC(kernel='linear',C=30, gamma='auto'), iris.data, iris.target, cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [70]:
cross_val_score(svm.SVC(kernel='sigmoid',C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.33333333, 0.1       , 0.        , 0.03333333, 0.        ])

In [71]:
import numpy as np

In [72]:
Kernels = ['rbf','linear','sigmoid']
C = [1,10,20]
avg_scores = {}
for kval in Kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval+'_'+str(cval)] = np.average(cv_scores)

In [73]:
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'sigmoid_1': 0.09333333333333334,
 'sigmoid_10': 0.09333333333333334,
 'sigmoid_20': 0.09333333333333334}

In [74]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel': ['rbf','linear','sigmoid']
}, cv=5, return_train_score = False)

In [75]:
clf.fit(iris.data, iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20],
                         'kernel': ['rbf', 'linear', 'sigmoid']})

In [76]:
clf.cv_results_

{'mean_fit_time': array([0.00086246, 0.00099173, 0.00160022, 0.        , 0.        ,
        0.00313187, 0.        , 0.00312524, 0.        ]),
 'std_fit_time': array([2.93625411e-04, 1.02210131e-05, 4.87702309e-04, 0.00000000e+00,
        0.00000000e+00, 6.26373291e-03, 0.00000000e+00, 6.25047684e-03,
        0.00000000e+00]),
 'mean_score_time': array([0.00090137, 0.00040751, 0.00039907, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]),
 'std_score_time': array([0.00047146, 0.00049912, 0.00048875, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'sigmoid', 'rbf', 'linear', 'sigmoid',
                    'rbf', 'linear', 'sigmoid'],
              mask=[

In [77]:
df_cv = pd.DataFrame(clf.cv_results_)
df_cv

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000862      0.000294         0.000901        0.000471       1   
1       0.000992      0.000010         0.000408        0.000499       1   
2       0.001600      0.000488         0.000399        0.000489       1   
3       0.000000      0.000000         0.000000        0.000000      10   
4       0.000000      0.000000         0.000000        0.000000      10   
5       0.003132      0.006264         0.000000        0.000000      10   
6       0.000000      0.000000         0.000000        0.000000      20   
7       0.003125      0.006250         0.000000        0.000000      20   
8       0.000000      0.000000         0.000000        0.000000      20   

  param_kernel                          params  split0_test_score  \
0          rbf       {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear    {'C': 1, 'kernel': 'linear'}           0.966667   
2      sigmoid   {'C': 1, 'kernel': 'sigmoid'}           0.333333   
3          rbf      {'C': 10, 'kernel': 'rbf'}           0.966667   
4       linear   {'C': 10, 'kernel': 'linear'}           1.000000   
5      sigmoid  {'C': 10, 'kernel': 'sigmoid'}           0.333333   
6          rbf      {'C': 20, 'kernel': 'rbf'}           0.966667   
7       linear   {'C': 20, 'kernel': 'linear'}           1.000000   
8      sigmoid  {'C': 20, 'kernel': 'sigmoid'}           0.333333   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                0.1           0.000000           0.033333                0.0   
3                1.0           0.966667           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                0.1           0.000000           0.033333                0.0   
6                1.0           0.900000           0.966667                1.0   
7                1.0           0.900000           0.933333                1.0   
8                0.1           0.000000           0.033333                0.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.093333        0.125433                7  
3         0.980000        0.016330                1  
4         0.973333        0.038873                4  
5         0.093333        0.125433                7  
6         0.966667        0.036515                5  
7         0.966667        0.042164                6  
8         0.093333        0.125433                7

In [78]:
df_cv[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2       1      sigmoid         0.093333
3      10          rbf         0.980000
4      10       linear         0.973333
5      10      sigmoid         0.093333
6      20          rbf         0.966667
7      20       linear         0.966667
8      20      sigmoid         0.093333

In [79]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [80]:
clf.best_score_

0.9800000000000001

In [81]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [82]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel': ['rbf','linear','sigmoid']
},
     cv=5,
     return_train_score = False,
     n_iter=2
                       )
                        

In [83]:
rs.fit(iris.data, iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'sigmoid']})

In [84]:
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf             0.98
1       1          rbf             0.98

In [85]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [86]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1,10,20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [87]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [88]:
df = pd.DataFrame(scores,columns=['model', 'best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}