In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [6]:
data = pd.read_csv('multivariate.csv')
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
import math
median_bedrooms = math.floor(data.bedrooms.median())
median_bedrooms

3

In [11]:
data.bedrooms = data.bedrooms.fillna(median_bedrooms)

In [12]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
model = linear_model.LinearRegression()
model.fit(data[['area','bedrooms', 'age']], data.price)

LinearRegression()

In [16]:
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [17]:
model.intercept_

383725.0

In [23]:
model.predict([[3000,4,40]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([418375.])

In [24]:
137.25*3000+-26025*4+-6825*40+383725

418375.0

In [25]:
model.predict([[2000,4,5]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([520000.])

In [26]:
137.25*2000+-26025*4+-6825*5+383725

520000.0

In [28]:
model.predict([[4000,5,1]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([795775.])

In [29]:
137.25*4000+-26025*5+-6825*1+383725

795775.0